// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package dbgen

import (
	"context"
	"time"
)

const countUndismissedAlerts = `-- name: CountUndismissedAlerts :one
SELECT COUNT(*) FROM article_alerts aa
JOIN news_alerts na ON aa.alert_id = na.id
WHERE na.user_id = ? AND aa.dismissed = 0
`

func (q *Queries) CountUndismissedAlerts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUndismissedAlerts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUndismissedForAlert = `-- name: CountUndismissedForAlert :one
SELECT COUNT(*) FROM article_alerts WHERE alert_id = ? AND dismissed = 0
`

func (q *Queries) CountUndismissedForAlert(ctx context.Context, alertID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUndismissedForAlert, alertID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO news_alerts (user_id, name, pattern, is_regex, match_field)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, pattern, is_regex, match_field, created_at
`

type CreateAlertParams struct {
	UserID     int64  `json:"user_id"`
	Name       string `json:"name"`
	Pattern    string `json:"pattern"`
	IsRegex    int64  `json:"is_regex"`
	MatchField string `json:"match_field"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (NewsAlert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.UserID,
		arg.Name,
		arg.Pattern,
		arg.IsRegex,
		arg.MatchField,
	)
	var i NewsAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Pattern,
		&i.IsRegex,
		&i.MatchField,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM news_alerts WHERE id = ? AND user_id = ?
`

type DeleteAlertParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteAlert(ctx context.Context, arg DeleteAlertParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlert, arg.ID, arg.UserID)
	return err
}

const dismissAllForAlert = `-- name: DismissAllForAlert :exec
UPDATE article_alerts SET dismissed = 1
WHERE alert_id = ? AND alert_id IN (SELECT id FROM news_alerts WHERE user_id = ?)
`

type DismissAllForAlertParams struct {
	AlertID int64 `json:"alert_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) DismissAllForAlert(ctx context.Context, arg DismissAllForAlertParams) error {
	_, err := q.db.ExecContext(ctx, dismissAllForAlert, arg.AlertID, arg.UserID)
	return err
}

const dismissArticleAlert = `-- name: DismissArticleAlert :exec
UPDATE article_alerts SET dismissed = 1
WHERE article_alerts.id = ? AND alert_id IN (SELECT news_alerts.id FROM news_alerts WHERE user_id = ?)
`

type DismissArticleAlertParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DismissArticleAlert(ctx context.Context, arg DismissArticleAlertParams) error {
	_, err := q.db.ExecContext(ctx, dismissArticleAlert, arg.ID, arg.UserID)
	return err
}

const getAlert = `-- name: GetAlert :one
SELECT id, user_id, name, pattern, is_regex, match_field, created_at FROM news_alerts WHERE id = ? AND user_id = ?
`

type GetAlertParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetAlert(ctx context.Context, arg GetAlertParams) (NewsAlert, error) {
	row := q.db.QueryRowContext(ctx, getAlert, arg.ID, arg.UserID)
	var i NewsAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Pattern,
		&i.IsRegex,
		&i.MatchField,
		&i.CreatedAt,
	)
	return i, err
}

const insertArticleAlert = `-- name: InsertArticleAlert :exec
INSERT OR IGNORE INTO article_alerts (article_id, alert_id) VALUES (?, ?)
`

type InsertArticleAlertParams struct {
	ArticleID int64 `json:"article_id"`
	AlertID   int64 `json:"alert_id"`
}

func (q *Queries) InsertArticleAlert(ctx context.Context, arg InsertArticleAlertParams) error {
	_, err := q.db.ExecContext(ctx, insertArticleAlert, arg.ArticleID, arg.AlertID)
	return err
}

const listAlertArticles = `-- name: ListAlertArticles :many
SELECT aa.id, aa.article_id, aa.alert_id, aa.matched_at, aa.dismissed,
       a.title as article_title, a.url as article_url, a.summary as article_summary,
       a.published_at as article_published_at,
       f.name as feed_name
FROM article_alerts aa
JOIN articles a ON aa.article_id = a.id
JOIN feeds f ON a.feed_id = f.id
JOIN news_alerts na ON aa.alert_id = na.id
WHERE aa.alert_id = ? AND na.user_id = ?
ORDER BY aa.matched_at DESC
LIMIT ? OFFSET ?
`

type ListAlertArticlesParams struct {
	AlertID int64 `json:"alert_id"`
	UserID  int64 `json:"user_id"`
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
}

type ListAlertArticlesRow struct {
	ID                 int64      `json:"id"`
	ArticleID          int64      `json:"article_id"`
	AlertID            int64      `json:"alert_id"`
	MatchedAt          time.Time  `json:"matched_at"`
	Dismissed          int64      `json:"dismissed"`
	ArticleTitle       string     `json:"article_title"`
	ArticleUrl         *string    `json:"article_url"`
	ArticleSummary     *string    `json:"article_summary"`
	ArticlePublishedAt *time.Time `json:"article_published_at"`
	FeedName           string     `json:"feed_name"`
}

func (q *Queries) ListAlertArticles(ctx context.Context, arg ListAlertArticlesParams) ([]ListAlertArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertArticles,
		arg.AlertID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertArticlesRow{}
	for rows.Next() {
		var i ListAlertArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.AlertID,
			&i.MatchedAt,
			&i.Dismissed,
			&i.ArticleTitle,
			&i.ArticleUrl,
			&i.ArticleSummary,
			&i.ArticlePublishedAt,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertArticlesGrouped = `-- name: ListAlertArticlesGrouped :many
SELECT aa.id, aa.article_id, aa.alert_id, aa.matched_at, aa.dismissed,
       a.title as article_title, a.url as article_url, a.summary as article_summary,
       a.published_at as article_published_at,
       f.name as feed_name,
       na.name as alert_name
FROM article_alerts aa
JOIN articles a ON aa.article_id = a.id
JOIN feeds f ON a.feed_id = f.id
JOIN news_alerts na ON aa.alert_id = na.id
WHERE na.user_id = ? AND aa.dismissed = 0
ORDER BY na.id, aa.matched_at DESC
LIMIT ? OFFSET ?
`

type ListAlertArticlesGroupedParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAlertArticlesGroupedRow struct {
	ID                 int64      `json:"id"`
	ArticleID          int64      `json:"article_id"`
	AlertID            int64      `json:"alert_id"`
	MatchedAt          time.Time  `json:"matched_at"`
	Dismissed          int64      `json:"dismissed"`
	ArticleTitle       string     `json:"article_title"`
	ArticleUrl         *string    `json:"article_url"`
	ArticleSummary     *string    `json:"article_summary"`
	ArticlePublishedAt *time.Time `json:"article_published_at"`
	FeedName           string     `json:"feed_name"`
	AlertName          string     `json:"alert_name"`
}

func (q *Queries) ListAlertArticlesGrouped(ctx context.Context, arg ListAlertArticlesGroupedParams) ([]ListAlertArticlesGroupedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertArticlesGrouped, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertArticlesGroupedRow{}
	for rows.Next() {
		var i ListAlertArticlesGroupedRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.AlertID,
			&i.MatchedAt,
			&i.Dismissed,
			&i.ArticleTitle,
			&i.ArticleUrl,
			&i.ArticleSummary,
			&i.ArticlePublishedAt,
			&i.FeedName,
			&i.AlertName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByUser = `-- name: ListAlertsByUser :many
SELECT id, user_id, name, pattern, is_regex, match_field, created_at FROM news_alerts WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAlertsByUser(ctx context.Context, userID int64) ([]NewsAlert, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsAlert{}
	for rows.Next() {
		var i NewsAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Pattern,
			&i.IsRegex,
			&i.MatchField,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByFeedForAlerts = `-- name: ListUnreadArticlesByFeedForAlerts :many
SELECT a.id, a.feed_id, a.title, a.url, a.author, a.content, a.summary,
       a.published_at, a.fetched_at
FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.feed_id = ? AND f.user_id = ? AND a.is_read = 0
ORDER BY a.fetched_at DESC
`

type ListUnreadArticlesByFeedForAlertsParams struct {
	FeedID int64  `json:"feed_id"`
	UserID *int64 `json:"user_id"`
}

type ListUnreadArticlesByFeedForAlertsRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
}

func (q *Queries) ListUnreadArticlesByFeedForAlerts(ctx context.Context, arg ListUnreadArticlesByFeedForAlertsParams) ([]ListUnreadArticlesByFeedForAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByFeedForAlerts, arg.FeedID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByFeedForAlertsRow{}
	for rows.Next() {
		var i ListUnreadArticlesByFeedForAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undismissArticleAlert = `-- name: UndismissArticleAlert :exec
UPDATE article_alerts SET dismissed = 0
WHERE article_alerts.id = ? AND alert_id IN (SELECT news_alerts.id FROM news_alerts WHERE user_id = ?)
`

type UndismissArticleAlertParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UndismissArticleAlert(ctx context.Context, arg UndismissArticleAlertParams) error {
	_, err := q.db.ExecContext(ctx, undismissArticleAlert, arg.ID, arg.UserID)
	return err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE news_alerts
SET name = ?, pattern = ?, is_regex = ?, match_field = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, name, pattern, is_regex, match_field, created_at
`

type UpdateAlertParams struct {
	Name       string `json:"name"`
	Pattern    string `json:"pattern"`
	IsRegex    int64  `json:"is_regex"`
	MatchField string `json:"match_field"`
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (NewsAlert, error) {
	row := q.db.QueryRowContext(ctx, updateAlert,
		arg.Name,
		arg.Pattern,
		arg.IsRegex,
		arg.MatchField,
		arg.ID,
		arg.UserID,
	)
	var i NewsAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Pattern,
		&i.IsRegex,
		&i.MatchField,
		&i.CreatedAt,
	)
	return i, err
}
