// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countOldUnstarredArticles = `-- name: CountOldUnstarredArticles :one
SELECT COUNT(*) FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 0 
  AND a.id NOT IN (SELECT article_id FROM queue_articles)
  AND a.fetched_at < datetime('now', '-' || ? || ' days')
  AND f.user_id = ?
`

type CountOldUnstarredArticlesParams struct {
	Column1 *string `json:"column_1"`
	UserID  *int64  `json:"user_id"`
}

func (q *Queries) CountOldUnstarredArticles(ctx context.Context, arg CountOldUnstarredArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOldUnstarredArticles, arg.Column1, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOldUnstarredArticlesGlobal = `-- name: CountOldUnstarredArticlesGlobal :one
SELECT COUNT(*) FROM articles
WHERE is_starred = 0 
  AND id NOT IN (SELECT article_id FROM queue_articles)
  AND fetched_at < datetime('now', '-' || ? || ' days')
`

func (q *Queries) CountOldUnstarredArticlesGlobal(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOldUnstarredArticlesGlobal, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (feed_id, guid, title, url, author, content, summary, image_url, published_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feed_id, guid) DO UPDATE SET
  title = excluded.title,
  url = excluded.url,
  author = excluded.author,
  content = excluded.content,
  summary = excluded.summary,
  image_url = excluded.image_url,
  published_at = excluded.published_at
RETURNING id, feed_id, guid, title, url, author, content, summary, image_url, published_at, fetched_at, is_read, is_starred
`

type CreateArticleParams struct {
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.FeedID,
		arg.Guid,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.ImageUrl,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.IsRead,
		&i.IsStarred,
	)
	return i, err
}

const deleteOldUnstarredArticles = `-- name: DeleteOldUnstarredArticles :execresult
DELETE FROM articles
WHERE articles.is_starred = 0 
  AND articles.id NOT IN (SELECT article_id FROM queue_articles)
  AND articles.fetched_at < datetime('now', '-' || ? || ' days')
  AND articles.feed_id IN (SELECT id FROM feeds WHERE feeds.user_id = ?)
`

type DeleteOldUnstarredArticlesParams struct {
	Column1 *string `json:"column_1"`
	UserID  *int64  `json:"user_id"`
}

func (q *Queries) DeleteOldUnstarredArticles(ctx context.Context, arg DeleteOldUnstarredArticlesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldUnstarredArticles, arg.Column1, arg.UserID)
}

const deleteOldUnstarredArticlesGlobal = `-- name: DeleteOldUnstarredArticlesGlobal :execresult
DELETE FROM articles
WHERE is_starred = 0 
  AND id NOT IN (SELECT article_id FROM queue_articles)
  AND fetched_at < datetime('now', '-' || ? || ' days')
`

// For background cleanup - deletes across all users
func (q *Queries) DeleteOldUnstarredArticlesGlobal(ctx context.Context, dollar_1 *string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldUnstarredArticlesGlobal, dollar_1)
}

const getArticle = `-- name: GetArticle :one
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.id = ? AND f.user_id = ?
`

type GetArticleParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, arg.ID, arg.UserID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.IsRead,
		&i.IsStarred,
	)
	return i, err
}

const getArticleWithFeed = `-- name: GetArticleWithFeed :one
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.id = ? AND f.user_id = ?
`

type GetArticleWithFeedParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

type GetArticleWithFeedRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) GetArticleWithFeed(ctx context.Context, arg GetArticleWithFeedParams) (GetArticleWithFeedRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleWithFeed, arg.ID, arg.UserID)
	var i GetArticleWithFeedRow
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.IsRead,
		&i.IsStarred,
		&i.FeedName,
	)
	return i, err
}

const getOldestArticleDate = `-- name: GetOldestArticleDate :one
SELECT MIN(a.fetched_at) FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 0 AND f.user_id = ?
`

func (q *Queries) GetOldestArticleDate(ctx context.Context, userID *int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOldestArticleDate, userID)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getOldestArticleDateGlobal = `-- name: GetOldestArticleDateGlobal :one
SELECT MIN(fetched_at) FROM articles WHERE is_starred = 0
`

func (q *Queries) GetOldestArticleDateGlobal(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOldestArticleDateGlobal)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getStarredCount = `-- name: GetStarredCount :one
SELECT COUNT(*) as count FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 1 AND f.user_id = ?
`

func (q *Queries) GetStarredCount(ctx context.Context, userID *int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStarredCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) as count FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_read = 0 AND f.user_id = ?
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID *int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesParams struct {
	UserID *int64 `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategory = `-- name: ListArticlesByCategory :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesByCategoryParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

type ListArticlesByCategoryRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByCategory(ctx context.Context, arg ListArticlesByCategoryParams) ([]ListArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByCategory,
		arg.CategoryID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategoryRow{}
	for rows.Next() {
		var i ListArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategoryCursor = `-- name: ListArticlesByCategoryCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListArticlesByCategoryCursorParams struct {
	CategoryID   int64      `json:"category_id"`
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListArticlesByCategoryCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByCategoryCursor(ctx context.Context, arg ListArticlesByCategoryCursorParams) ([]ListArticlesByCategoryCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByCategoryCursor,
		arg.CategoryID,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategoryCursorRow{}
	for rows.Next() {
		var i ListArticlesByCategoryCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByFeed = `-- name: ListArticlesByFeed :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.feed_id = ? AND f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesByFeedParams struct {
	FeedID int64  `json:"feed_id"`
	UserID *int64 `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListArticlesByFeedRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByFeed(ctx context.Context, arg ListArticlesByFeedParams) ([]ListArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByFeed,
		arg.FeedID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByFeedRow{}
	for rows.Next() {
		var i ListArticlesByFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByFeedCursor = `-- name: ListArticlesByFeedCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.feed_id = ? AND f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListArticlesByFeedCursorParams struct {
	FeedID       int64      `json:"feed_id"`
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListArticlesByFeedCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByFeedCursor(ctx context.Context, arg ListArticlesByFeedCursorParams) ([]ListArticlesByFeedCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByFeedCursor,
		arg.FeedID,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByFeedCursorRow{}
	for rows.Next() {
		var i ListArticlesByFeedCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesCursor = `-- name: ListArticlesCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListArticlesCursorParams struct {
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListArticlesCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesCursor(ctx context.Context, arg ListArticlesCursorParams) ([]ListArticlesCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesCursor,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesCursorRow{}
	for rows.Next() {
		var i ListArticlesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredArticles = `-- name: ListStarredArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 1 AND f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListStarredArticlesParams struct {
	UserID *int64 `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListStarredArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListStarredArticles(ctx context.Context, arg ListStarredArticlesParams) ([]ListStarredArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStarredArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStarredArticlesRow{}
	for rows.Next() {
		var i ListStarredArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredArticlesCursor = `-- name: ListStarredArticlesCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 1 AND f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListStarredArticlesCursorParams struct {
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListStarredArticlesCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListStarredArticlesCursor(ctx context.Context, arg ListStarredArticlesCursorParams) ([]ListStarredArticlesCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listStarredArticlesCursor,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStarredArticlesCursorRow{}
	for rows.Next() {
		var i ListStarredArticlesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticles = `-- name: ListUnreadArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_read = 0 AND f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListUnreadArticlesParams struct {
	UserID *int64 `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListUnreadArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticles(ctx context.Context, arg ListUnreadArticlesParams) ([]ListUnreadArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesRow{}
	for rows.Next() {
		var i ListUnreadArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByCategory = `-- name: ListUnreadArticlesByCategory :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0 AND f.user_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListUnreadArticlesByCategoryParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

type ListUnreadArticlesByCategoryRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticlesByCategory(ctx context.Context, arg ListUnreadArticlesByCategoryParams) ([]ListUnreadArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByCategory,
		arg.CategoryID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByCategoryRow{}
	for rows.Next() {
		var i ListUnreadArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByCategoryCursor = `-- name: ListUnreadArticlesByCategoryCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0 AND f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListUnreadArticlesByCategoryCursorParams struct {
	CategoryID   int64      `json:"category_id"`
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListUnreadArticlesByCategoryCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticlesByCategoryCursor(ctx context.Context, arg ListUnreadArticlesByCategoryCursorParams) ([]ListUnreadArticlesByCategoryCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByCategoryCursor,
		arg.CategoryID,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByCategoryCursorRow{}
	for rows.Next() {
		var i ListUnreadArticlesByCategoryCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByCategoryInternal = `-- name: ListUnreadArticlesByCategoryInternal :many
SELECT a.id, a.title, a.summary, a.author FROM articles a
JOIN feed_categories fc ON a.feed_id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0
`

type ListUnreadArticlesByCategoryInternalRow struct {
	ID      int64   `json:"id"`
	Title   string  `json:"title"`
	Summary *string `json:"summary"`
	Author  *string `json:"author"`
}

// Used internally to apply exclusion rules when a new rule is created
func (q *Queries) ListUnreadArticlesByCategoryInternal(ctx context.Context, categoryID int64) ([]ListUnreadArticlesByCategoryInternalRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByCategoryInternal, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByCategoryInternalRow{}
	for rows.Next() {
		var i ListUnreadArticlesByCategoryInternalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByFeedInternal = `-- name: ListUnreadArticlesByFeedInternal :many
SELECT id, title, summary, author FROM articles
WHERE feed_id = ? AND is_read = 0
`

type ListUnreadArticlesByFeedInternalRow struct {
	ID      int64   `json:"id"`
	Title   string  `json:"title"`
	Summary *string `json:"summary"`
	Author  *string `json:"author"`
}

// Used internally (no user_id check) to apply exclusion rules after fetch
func (q *Queries) ListUnreadArticlesByFeedInternal(ctx context.Context, feedID int64) ([]ListUnreadArticlesByFeedInternalRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByFeedInternal, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByFeedInternalRow{}
	for rows.Next() {
		var i ListUnreadArticlesByFeedInternalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesCursor = `-- name: ListUnreadArticlesCursor :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_read = 0 AND f.user_id = ?
  AND (COALESCE(a.published_at, a.fetched_at) < ?
       OR (COALESCE(a.published_at, a.fetched_at) = ? AND a.id < ?))
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC, a.id DESC
LIMIT ?
`

type ListUnreadArticlesCursorParams struct {
	UserID       *int64     `json:"user_id"`
	BeforeTime   *time.Time `json:"before_time"`
	BeforeTimeEq *time.Time `json:"before_time_eq"`
	BeforeID     int64      `json:"before_id"`
	Limit        int64      `json:"limit"`
}

type ListUnreadArticlesCursorRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticlesCursor(ctx context.Context, arg ListUnreadArticlesCursorParams) ([]ListUnreadArticlesCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesCursor,
		arg.UserID,
		arg.BeforeTime,
		arg.BeforeTimeEq,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesCursorRow{}
	for rows.Next() {
		var i ListUnreadArticlesCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllArticlesRead = `-- name: MarkAllArticlesRead :exec
UPDATE articles SET is_read = 1 
WHERE is_read = 0 AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

func (q *Queries) MarkAllArticlesRead(ctx context.Context, userID *int64) error {
	_, err := q.db.ExecContext(ctx, markAllArticlesRead, userID)
	return err
}

const markAllArticlesReadOlderThan = `-- name: MarkAllArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
  AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

type MarkAllArticlesReadOlderThanParams struct {
	Column1 *string `json:"column_1"`
	UserID  *int64  `json:"user_id"`
}

func (q *Queries) MarkAllArticlesReadOlderThan(ctx context.Context, arg MarkAllArticlesReadOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, markAllArticlesReadOlderThan, arg.Column1, arg.UserID)
	return err
}

const markAllRead = `-- name: MarkAllRead :exec
UPDATE articles SET is_read = 1 
WHERE feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

func (q *Queries) MarkAllRead(ctx context.Context, userID *int64) error {
	_, err := q.db.ExecContext(ctx, markAllRead, userID)
	return err
}

const markArticleRead = `-- name: MarkArticleRead :exec
UPDATE articles SET is_read = 1 
WHERE articles.id = ? AND feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type MarkArticleReadParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleRead, arg.ID, arg.UserID)
	return err
}

const markArticleReadInternal = `-- name: MarkArticleReadInternal :exec
UPDATE articles SET is_read = 1 WHERE id = ?
`

// Mark a single article read without user_id check (for exclusion auto-marking)
func (q *Queries) MarkArticleReadInternal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArticleReadInternal, id)
	return err
}

const markArticleUnread = `-- name: MarkArticleUnread :exec
UPDATE articles SET is_read = 0 
WHERE articles.id = ? AND feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type MarkArticleUnreadParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) MarkArticleUnread(ctx context.Context, arg MarkArticleUnreadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleUnread, arg.ID, arg.UserID)
	return err
}

const markCategoryArticlesReadOlderThan = `-- name: MarkCategoryArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE feed_id IN (
    SELECT f.id FROM feeds f
    JOIN feed_categories fc ON f.id = fc.feed_id 
    WHERE fc.category_id = ? AND f.user_id = ?
) AND is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
`

type MarkCategoryArticlesReadOlderThanParams struct {
	CategoryID int64   `json:"category_id"`
	UserID     *int64  `json:"user_id"`
	Column3    *string `json:"column_3"`
}

func (q *Queries) MarkCategoryArticlesReadOlderThan(ctx context.Context, arg MarkCategoryArticlesReadOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, markCategoryArticlesReadOlderThan, arg.CategoryID, arg.UserID, arg.Column3)
	return err
}

const markCategoryRead = `-- name: MarkCategoryRead :exec
UPDATE articles SET is_read = 1 
WHERE feed_id IN (
  SELECT f.id FROM feeds f
  JOIN feed_categories fc ON f.id = fc.feed_id 
  WHERE fc.category_id = ? AND f.user_id = ?
)
`

type MarkCategoryReadParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) MarkCategoryRead(ctx context.Context, arg MarkCategoryReadParams) error {
	_, err := q.db.ExecContext(ctx, markCategoryRead, arg.CategoryID, arg.UserID)
	return err
}

const markFeedArticlesReadOlderThan = `-- name: MarkFeedArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE feed_id = ? AND is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
  AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

type MarkFeedArticlesReadOlderThanParams struct {
	FeedID  int64   `json:"feed_id"`
	Column2 *string `json:"column_2"`
	UserID  *int64  `json:"user_id"`
}

func (q *Queries) MarkFeedArticlesReadOlderThan(ctx context.Context, arg MarkFeedArticlesReadOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, markFeedArticlesReadOlderThan, arg.FeedID, arg.Column2, arg.UserID)
	return err
}

const markFeedRead = `-- name: MarkFeedRead :exec
UPDATE articles SET is_read = 1 
WHERE feed_id = ? AND feed_id IN (SELECT id FROM feeds WHERE user_id = ?)
`

type MarkFeedReadParams struct {
	FeedID int64  `json:"feed_id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) MarkFeedRead(ctx context.Context, arg MarkFeedReadParams) error {
	_, err := q.db.ExecContext(ctx, markFeedRead, arg.FeedID, arg.UserID)
	return err
}

const searchArticles = `-- name: SearchArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE f.user_id = ? AND (a.title LIKE '%' || ? || '%' OR a.content LIKE '%' || ? || '%')
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type SearchArticlesParams struct {
	UserID  *int64  `json:"user_id"`
	Column2 *string `json:"column_2"`
	Column3 *string `json:"column_3"`
	Limit   int64   `json:"limit"`
	Offset  int64   `json:"offset"`
}

type SearchArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticles,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArticlesByCategory = `-- name: SearchArticlesByCategory :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND f.user_id = ? AND (a.title LIKE '%' || ? || '%' OR a.content LIKE '%' || ? || '%')
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type SearchArticlesByCategoryParams struct {
	CategoryID int64   `json:"category_id"`
	UserID     *int64  `json:"user_id"`
	Column3    *string `json:"column_3"`
	Column4    *string `json:"column_4"`
	Limit      int64   `json:"limit"`
	Offset     int64   `json:"offset"`
}

type SearchArticlesByCategoryRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) SearchArticlesByCategory(ctx context.Context, arg SearchArticlesByCategoryParams) ([]SearchArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticlesByCategory,
		arg.CategoryID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesByCategoryRow{}
	for rows.Next() {
		var i SearchArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArticlesByFeed = `-- name: SearchArticlesByFeed :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.feed_id = ? AND f.user_id = ? AND (a.title LIKE '%' || ? || '%' OR a.content LIKE '%' || ? || '%')
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type SearchArticlesByFeedParams struct {
	FeedID  int64   `json:"feed_id"`
	UserID  *int64  `json:"user_id"`
	Column3 *string `json:"column_3"`
	Column4 *string `json:"column_4"`
	Limit   int64   `json:"limit"`
	Offset  int64   `json:"offset"`
}

type SearchArticlesByFeedRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) SearchArticlesByFeed(ctx context.Context, arg SearchArticlesByFeedParams) ([]SearchArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticlesByFeed,
		arg.FeedID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesByFeedRow{}
	for rows.Next() {
		var i SearchArticlesByFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleArticleStar = `-- name: ToggleArticleStar :exec
UPDATE articles SET is_starred = NOT is_starred 
WHERE articles.id = ? AND feed_id IN (SELECT feeds.id FROM feeds WHERE feeds.user_id = ?)
`

type ToggleArticleStarParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) ToggleArticleStar(ctx context.Context, arg ToggleArticleStarParams) error {
	_, err := q.db.ExecContext(ctx, toggleArticleStar, arg.ID, arg.UserID)
	return err
}
