// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const countOldUnstarredArticles = `-- name: CountOldUnstarredArticles :one
SELECT COUNT(*) FROM articles
WHERE is_starred = 0 
  AND fetched_at < datetime('now', '-' || ? || ' days')
`

func (q *Queries) CountOldUnstarredArticles(ctx context.Context, dollar_1 *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOldUnstarredArticles, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (feed_id, guid, title, url, author, content, summary, image_url, published_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feed_id, guid) DO UPDATE SET
  title = excluded.title,
  url = excluded.url,
  author = excluded.author,
  content = excluded.content,
  summary = excluded.summary,
  image_url = excluded.image_url,
  published_at = excluded.published_at
RETURNING id, feed_id, guid, title, url, author, content, summary, image_url, published_at, fetched_at, is_read, is_starred
`

type CreateArticleParams struct {
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.FeedID,
		arg.Guid,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.Content,
		arg.Summary,
		arg.ImageUrl,
		arg.PublishedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.IsRead,
		&i.IsStarred,
	)
	return i, err
}

const deleteOldUnstarredArticles = `-- name: DeleteOldUnstarredArticles :execresult
DELETE FROM articles
WHERE is_starred = 0 
  AND fetched_at < datetime('now', '-' || ? || ' days')
  AND id NOT IN (
    SELECT id FROM articles WHERE is_starred = 1
  )
`

func (q *Queries) DeleteOldUnstarredArticles(ctx context.Context, dollar_1 *string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOldUnstarredArticles, dollar_1)
}

const getArticle = `-- name: GetArticle :one
SELECT id, feed_id, guid, title, url, author, content, summary, image_url, published_at, fetched_at, is_read, is_starred FROM articles WHERE id = ?
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Guid,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Content,
		&i.Summary,
		&i.ImageUrl,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.IsRead,
		&i.IsStarred,
	)
	return i, err
}

const getOldestArticleDate = `-- name: GetOldestArticleDate :one
SELECT MIN(fetched_at) FROM articles WHERE is_starred = 0
`

func (q *Queries) GetOldestArticleDate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOldestArticleDate)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getStarredCount = `-- name: GetStarredCount :one
SELECT COUNT(*) as count FROM articles WHERE is_starred = 1
`

func (q *Queries) GetStarredCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStarredCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) as count FROM articles WHERE is_read = 0
`

func (q *Queries) GetUnreadCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCategory = `-- name: ListArticlesByCategory :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesByCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

type ListArticlesByCategoryRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByCategory(ctx context.Context, arg ListArticlesByCategoryParams) ([]ListArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByCategoryRow{}
	for rows.Next() {
		var i ListArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByFeed = `-- name: ListArticlesByFeed :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.feed_id = ?
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListArticlesByFeedParams struct {
	FeedID int64 `json:"feed_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListArticlesByFeedRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListArticlesByFeed(ctx context.Context, arg ListArticlesByFeedParams) ([]ListArticlesByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByFeed, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByFeedRow{}
	for rows.Next() {
		var i ListArticlesByFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredArticles = `-- name: ListStarredArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_starred = 1
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListStarredArticlesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListStarredArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListStarredArticles(ctx context.Context, arg ListStarredArticlesParams) ([]ListStarredArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStarredArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStarredArticlesRow{}
	for rows.Next() {
		var i ListStarredArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticles = `-- name: ListUnreadArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.is_read = 0
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListUnreadArticlesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUnreadArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticles(ctx context.Context, arg ListUnreadArticlesParams) ([]ListUnreadArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesRow{}
	for rows.Next() {
		var i ListUnreadArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadArticlesByCategory = `-- name: ListUnreadArticlesByCategory :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type ListUnreadArticlesByCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

type ListUnreadArticlesByCategoryRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) ListUnreadArticlesByCategory(ctx context.Context, arg ListUnreadArticlesByCategoryParams) ([]ListUnreadArticlesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadArticlesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadArticlesByCategoryRow{}
	for rows.Next() {
		var i ListUnreadArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllArticlesRead = `-- name: MarkAllArticlesRead :exec
UPDATE articles SET is_read = 1 WHERE is_read = 0
`

func (q *Queries) MarkAllArticlesRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllArticlesRead)
	return err
}

const markAllArticlesReadOlderThan = `-- name: MarkAllArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
`

func (q *Queries) MarkAllArticlesReadOlderThan(ctx context.Context, dollar_1 *string) error {
	_, err := q.db.ExecContext(ctx, markAllArticlesReadOlderThan, dollar_1)
	return err
}

const markAllRead = `-- name: MarkAllRead :exec
UPDATE articles SET is_read = 1
`

func (q *Queries) MarkAllRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllRead)
	return err
}

const markArticleRead = `-- name: MarkArticleRead :exec
UPDATE articles SET is_read = 1 WHERE id = ?
`

func (q *Queries) MarkArticleRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArticleRead, id)
	return err
}

const markArticleUnread = `-- name: MarkArticleUnread :exec
UPDATE articles SET is_read = 0 WHERE id = ?
`

func (q *Queries) MarkArticleUnread(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArticleUnread, id)
	return err
}

const markCategoryArticlesReadOlderThan = `-- name: MarkCategoryArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE feed_id IN (
    SELECT feed_id FROM feed_categories WHERE category_id = ?
) AND is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
`

type MarkCategoryArticlesReadOlderThanParams struct {
	CategoryID int64   `json:"category_id"`
	Column2    *string `json:"column_2"`
}

func (q *Queries) MarkCategoryArticlesReadOlderThan(ctx context.Context, arg MarkCategoryArticlesReadOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, markCategoryArticlesReadOlderThan, arg.CategoryID, arg.Column2)
	return err
}

const markCategoryRead = `-- name: MarkCategoryRead :exec
UPDATE articles SET is_read = 1 
WHERE feed_id IN (
  SELECT feed_id FROM feed_categories WHERE category_id = ?
)
`

func (q *Queries) MarkCategoryRead(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, markCategoryRead, categoryID)
	return err
}

const markFeedArticlesReadOlderThan = `-- name: MarkFeedArticlesReadOlderThan :exec
UPDATE articles SET is_read = 1 
WHERE feed_id = ? AND is_read = 0 
  AND COALESCE(published_at, fetched_at) < datetime('now', '-' || ? || ' days')
`

type MarkFeedArticlesReadOlderThanParams struct {
	FeedID  int64   `json:"feed_id"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) MarkFeedArticlesReadOlderThan(ctx context.Context, arg MarkFeedArticlesReadOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, markFeedArticlesReadOlderThan, arg.FeedID, arg.Column2)
	return err
}

const markFeedRead = `-- name: MarkFeedRead :exec
UPDATE articles SET is_read = 1 WHERE feed_id = ?
`

func (q *Queries) MarkFeedRead(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, markFeedRead, feedID)
	return err
}

const searchArticles = `-- name: SearchArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary, a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred, f.name as feed_name FROM articles a
JOIN feeds f ON a.feed_id = f.id
WHERE a.title LIKE '%' || ? || '%' OR a.content LIKE '%' || ? || '%'
ORDER BY COALESCE(a.published_at, a.fetched_at) DESC
LIMIT ? OFFSET ?
`

type SearchArticlesParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
	Limit   int64   `json:"limit"`
	Offset  int64   `json:"offset"`
}

type SearchArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArticles,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleArticleStar = `-- name: ToggleArticleStar :exec
UPDATE articles SET is_starred = NOT is_starred WHERE id = ?
`

func (q *Queries) ToggleArticleStar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleArticleStar, id)
	return err
}
