// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exclusions.sql

package dbgen

import (
	"context"
	"time"
)

const createExclusion = `-- name: CreateExclusion :one
INSERT INTO category_exclusions (category_id, exclusion_type, pattern, is_regex)
VALUES (?, ?, ?, ?)
RETURNING id, category_id, exclusion_type, pattern, is_regex, created_at
`

type CreateExclusionParams struct {
	CategoryID    int64  `json:"category_id"`
	ExclusionType string `json:"exclusion_type"`
	Pattern       string `json:"pattern"`
	IsRegex       *int64 `json:"is_regex"`
}

func (q *Queries) CreateExclusion(ctx context.Context, arg CreateExclusionParams) (CategoryExclusion, error) {
	row := q.db.QueryRowContext(ctx, createExclusion,
		arg.CategoryID,
		arg.ExclusionType,
		arg.Pattern,
		arg.IsRegex,
	)
	var i CategoryExclusion
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.ExclusionType,
		&i.Pattern,
		&i.IsRegex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategorySetting = `-- name: DeleteCategorySetting :exec
DELETE FROM category_settings 
WHERE category_settings.category_id = ? AND setting_key = ? 
  AND category_settings.category_id IN (SELECT categories.id FROM categories WHERE categories.user_id = ?)
`

type DeleteCategorySettingParams struct {
	CategoryID int64  `json:"category_id"`
	SettingKey string `json:"setting_key"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) DeleteCategorySetting(ctx context.Context, arg DeleteCategorySettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategorySetting, arg.CategoryID, arg.SettingKey, arg.UserID)
	return err
}

const deleteExclusion = `-- name: DeleteExclusion :exec
DELETE FROM category_exclusions 
WHERE category_exclusions.id = ? AND category_id IN (SELECT categories.id FROM categories WHERE categories.user_id = ?)
`

type DeleteExclusionParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteExclusion(ctx context.Context, arg DeleteExclusionParams) error {
	_, err := q.db.ExecContext(ctx, deleteExclusion, arg.ID, arg.UserID)
	return err
}

const deleteExclusionsByCategory = `-- name: DeleteExclusionsByCategory :exec
DELETE FROM category_exclusions WHERE category_id = ?
`

func (q *Queries) DeleteExclusionsByCategory(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteExclusionsByCategory, categoryID)
	return err
}

const getCategorySetting = `-- name: GetCategorySetting :one
SELECT cs.id, cs.category_id, cs.setting_key, cs.setting_value, cs.created_at, cs.user_id FROM category_settings cs
JOIN categories c ON cs.category_id = c.id
WHERE cs.category_id = ? AND cs.setting_key = ? AND c.user_id = ?
`

type GetCategorySettingParams struct {
	CategoryID int64  `json:"category_id"`
	SettingKey string `json:"setting_key"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) GetCategorySetting(ctx context.Context, arg GetCategorySettingParams) (CategorySetting, error) {
	row := q.db.QueryRowContext(ctx, getCategorySetting, arg.CategoryID, arg.SettingKey, arg.UserID)
	var i CategorySetting
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.SettingKey,
		&i.SettingValue,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getExclusion = `-- name: GetExclusion :one
SELECT e.id, e.category_id, e.exclusion_type, e.pattern, e.is_regex, e.created_at FROM category_exclusions e
JOIN categories c ON e.category_id = c.id
WHERE e.id = ? AND c.user_id = ?
`

type GetExclusionParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetExclusion(ctx context.Context, arg GetExclusionParams) (CategoryExclusion, error) {
	row := q.db.QueryRowContext(ctx, getExclusion, arg.ID, arg.UserID)
	var i CategoryExclusion
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.ExclusionType,
		&i.Pattern,
		&i.IsRegex,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCategorySettings = `-- name: ListAllCategorySettings :many
SELECT cs.id, cs.category_id, cs.setting_key, cs.setting_value, cs.created_at, cs.user_id FROM category_settings cs
JOIN categories c ON cs.category_id = c.id
WHERE c.user_id = ?
ORDER BY c.name, cs.setting_key
`

func (q *Queries) ListAllCategorySettings(ctx context.Context, userID *int64) ([]CategorySetting, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategorySettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategorySetting{}
	for rows.Next() {
		var i CategorySetting
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.SettingKey,
			&i.SettingValue,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllExclusions = `-- name: ListAllExclusions :many
SELECT e.id, e.category_id, e.exclusion_type, e.pattern, e.is_regex, e.created_at, c.name as category_name 
FROM category_exclusions e
JOIN categories c ON e.category_id = c.id
WHERE c.user_id = ?
ORDER BY c.name, e.exclusion_type, e.pattern
`

type ListAllExclusionsRow struct {
	ID            int64     `json:"id"`
	CategoryID    int64     `json:"category_id"`
	ExclusionType string    `json:"exclusion_type"`
	Pattern       string    `json:"pattern"`
	IsRegex       *int64    `json:"is_regex"`
	CreatedAt     time.Time `json:"created_at"`
	CategoryName  string    `json:"category_name"`
}

func (q *Queries) ListAllExclusions(ctx context.Context, userID *int64) ([]ListAllExclusionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllExclusions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllExclusionsRow{}
	for rows.Next() {
		var i ListAllExclusionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.ExclusionType,
			&i.Pattern,
			&i.IsRegex,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategorySettings = `-- name: ListCategorySettings :many
SELECT cs.id, cs.category_id, cs.setting_key, cs.setting_value, cs.created_at, cs.user_id FROM category_settings cs
JOIN categories c ON cs.category_id = c.id
WHERE cs.category_id = ? AND c.user_id = ?
`

type ListCategorySettingsParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) ListCategorySettings(ctx context.Context, arg ListCategorySettingsParams) ([]CategorySetting, error) {
	rows, err := q.db.QueryContext(ctx, listCategorySettings, arg.CategoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategorySetting{}
	for rows.Next() {
		var i CategorySetting
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.SettingKey,
			&i.SettingValue,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExclusionsByCategory = `-- name: ListExclusionsByCategory :many
SELECT e.id, e.category_id, e.exclusion_type, e.pattern, e.is_regex, e.created_at FROM category_exclusions e
JOIN categories c ON e.category_id = c.id
WHERE e.category_id = ? AND c.user_id = ?
ORDER BY e.exclusion_type, e.pattern
`

type ListExclusionsByCategoryParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) ListExclusionsByCategory(ctx context.Context, arg ListExclusionsByCategoryParams) ([]CategoryExclusion, error) {
	rows, err := q.db.QueryContext(ctx, listExclusionsByCategory, arg.CategoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryExclusion{}
	for rows.Next() {
		var i CategoryExclusion
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.ExclusionType,
			&i.Pattern,
			&i.IsRegex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategorySetting = `-- name: SetCategorySetting :exec
INSERT INTO category_settings (category_id, setting_key, setting_value)
VALUES (?, ?, ?)
ON CONFLICT(category_id, setting_key) DO UPDATE SET setting_value = excluded.setting_value
`

type SetCategorySettingParams struct {
	CategoryID   int64   `json:"category_id"`
	SettingKey   string  `json:"setting_key"`
	SettingValue *string `json:"setting_value"`
}

func (q *Queries) SetCategorySetting(ctx context.Context, arg SetCategorySettingParams) error {
	_, err := q.db.ExecContext(ctx, setCategorySetting, arg.CategoryID, arg.SettingKey, arg.SettingValue)
	return err
}

const updateExclusion = `-- name: UpdateExclusion :exec
UPDATE category_exclusions SET pattern = ?, is_regex = ? 
WHERE category_exclusions.id = ? AND category_id IN (SELECT categories.id FROM categories WHERE categories.user_id = ?)
`

type UpdateExclusionParams struct {
	Pattern string `json:"pattern"`
	IsRegex *int64 `json:"is_regex"`
	ID      int64  `json:"id"`
	UserID  *int64 `json:"user_id"`
}

func (q *Queries) UpdateExclusion(ctx context.Context, arg UpdateExclusionParams) error {
	_, err := q.db.ExecContext(ctx, updateExclusion,
		arg.Pattern,
		arg.IsRegex,
		arg.ID,
		arg.UserID,
	)
	return err
}
