// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package dbgen

import (
	"context"
	"time"
)

const addFeedToCategory = `-- name: AddFeedToCategory :exec
INSERT OR IGNORE INTO feed_categories (feed_id, category_id) VALUES (?, ?)
`

type AddFeedToCategoryParams struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) AddFeedToCategory(ctx context.Context, arg AddFeedToCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addFeedToCategory, arg.FeedID, arg.CategoryID)
	return err
}

const clearFeedCategories = `-- name: ClearFeedCategories :exec
DELETE FROM feed_categories WHERE feed_id = ?
`

func (q *Queries) ClearFeedCategories(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, clearFeedCategories, feedID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, url, feed_type, scraper_module, scraper_config, fetch_interval_minutes)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at
`

type CreateFeedParams struct {
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	FeedType             string  `json:"feed_type"`
	ScraperModule        *string `json:"scraper_module"`
	ScraperConfig        *string `json:"scraper_config"`
	FetchIntervalMinutes *int64  `json:"fetch_interval_minutes"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Name,
		arg.Url,
		arg.FeedType,
		arg.ScraperModule,
		arg.ScraperConfig,
		arg.FetchIntervalMinutes,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = ?
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, created_at FROM categories WHERE name = ?
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCategoryUnreadCount = `-- name: GetCategoryUnreadCount :one
SELECT COUNT(*) as count FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0
`

func (q *Queries) GetCategoryUnreadCount(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryUnreadCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeed = `-- name: GetFeed :one
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at FROM feeds WHERE id = ?
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at FROM feeds WHERE url = ?
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedCategories = `-- name: GetFeedCategories :many
SELECT c.id, c.name, c.created_at FROM categories c
JOIN feed_categories fc ON c.id = fc.category_id
WHERE fc.feed_id = ?
`

func (q *Queries) GetFeedCategories(ctx context.Context, feedID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getFeedCategories, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedUnreadCount = `-- name: GetFeedUnreadCount :one
SELECT COUNT(*) as count FROM articles WHERE feed_id = ? AND is_read = 0
`

func (q *Queries) GetFeedUnreadCount(ctx context.Context, feedID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedUnreadCount, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, created_at FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at FROM feeds ORDER BY name
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByCategory = `-- name: ListFeedsByCategory :many
SELECT f.id, f.name, f.url, f.feed_type, f.scraper_module, f.scraper_config, f.last_fetched_at, f.last_error, f.fetch_interval_minutes, f.created_at, f.updated_at FROM feeds f
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ?
ORDER BY f.name
`

func (q *Queries) ListFeedsByCategory(ctx context.Context, categoryID int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsToFetch = `-- name: ListFeedsToFetch :many
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at FROM feeds 
WHERE last_fetched_at IS NULL 
   OR datetime(last_fetched_at, '+' || fetch_interval_minutes || ' minutes') < datetime('now')
ORDER BY last_fetched_at NULLS FIRST
`

func (q *Queries) ListFeedsToFetch(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsToFetch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorizedFeeds = `-- name: ListUncategorizedFeeds :many
SELECT f.id, f.name, f.url, f.feed_type, f.scraper_module, f.scraper_config, f.last_fetched_at, f.last_error, f.fetch_interval_minutes, f.created_at, f.updated_at FROM feeds f
WHERE NOT EXISTS (
  SELECT 1 FROM feed_categories fc WHERE fc.feed_id = f.id
)
ORDER BY f.name
`

func (q *Queries) ListUncategorizedFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listUncategorizedFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedFromCategory = `-- name: RemoveFeedFromCategory :exec
DELETE FROM feed_categories WHERE feed_id = ? AND category_id = ?
`

type RemoveFeedFromCategoryParams struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) RemoveFeedFromCategory(ctx context.Context, arg RemoveFeedFromCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeFeedFromCategory, arg.FeedID, arg.CategoryID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.ID)
	return err
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds SET name = ?, url = ?, feed_type = ?, scraper_module = ?, scraper_config = ?, fetch_interval_minutes = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateFeedParams struct {
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	FeedType             string  `json:"feed_type"`
	ScraperModule        *string `json:"scraper_module"`
	ScraperConfig        *string `json:"scraper_config"`
	FetchIntervalMinutes *int64  `json:"fetch_interval_minutes"`
	ID                   int64   `json:"id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed,
		arg.Name,
		arg.Url,
		arg.FeedType,
		arg.ScraperModule,
		arg.ScraperConfig,
		arg.FetchIntervalMinutes,
		arg.ID,
	)
	return err
}

const updateFeedLastFetched = `-- name: UpdateFeedLastFetched :exec
UPDATE feeds SET last_fetched_at = ?, last_error = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateFeedLastFetchedParams struct {
	LastFetchedAt *time.Time `json:"last_fetched_at"`
	LastError     *string    `json:"last_error"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateFeedLastFetched(ctx context.Context, arg UpdateFeedLastFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedLastFetched, arg.LastFetchedAt, arg.LastError, arg.ID)
	return err
}
