// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package dbgen

import (
	"context"
	"time"
)

const addFeedToCategory = `-- name: AddFeedToCategory :exec
INSERT OR IGNORE INTO feed_categories (feed_id, category_id) VALUES (?, ?)
`

type AddFeedToCategoryParams struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) AddFeedToCategory(ctx context.Context, arg AddFeedToCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addFeedToCategory, arg.FeedID, arg.CategoryID)
	return err
}

const clearFeedCategories = `-- name: ClearFeedCategories :exec
DELETE FROM feed_categories WHERE feed_id = ?
`

func (q *Queries) ClearFeedCategories(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, clearFeedCategories, feedID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, user_id) VALUES (?, ?) RETURNING id, name, created_at, user_id, sort_order, parent_id
`

type CreateCategoryParams struct {
	Name   string `json:"name"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UserID,
		&i.SortOrder,
		&i.ParentID,
	)
	return i, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, url, feed_type, scraper_module, scraper_config, fetch_interval_minutes, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at, user_id, content_filters, site_url
`

type CreateFeedParams struct {
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	FeedType             string  `json:"feed_type"`
	ScraperModule        *string `json:"scraper_module"`
	ScraperConfig        *string `json:"scraper_config"`
	FetchIntervalMinutes *int64  `json:"fetch_interval_minutes"`
	UserID               *int64  `json:"user_id"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Name,
		arg.Url,
		arg.FeedType,
		arg.ScraperModule,
		arg.ScraperConfig,
		arg.FetchIntervalMinutes,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ContentFilters,
		&i.SiteUrl,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ? AND user_id = ?
`

type DeleteCategoryParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = ? AND user_id = ?
`

type DeleteFeedParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, created_at, user_id, sort_order, parent_id FROM categories WHERE id = ? AND user_id = ?
`

type GetCategoryParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UserID,
		&i.SortOrder,
		&i.ParentID,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, created_at, user_id, sort_order, parent_id FROM categories WHERE name = ? AND user_id = ?
`

type GetCategoryByNameParams struct {
	Name   string `json:"name"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, arg.Name, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UserID,
		&i.SortOrder,
		&i.ParentID,
	)
	return i, err
}

const getCategoryUnreadCount = `-- name: GetCategoryUnreadCount :one
SELECT COUNT(*) as count FROM articles a
JOIN feeds f ON a.feed_id = f.id
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND a.is_read = 0
`

func (q *Queries) GetCategoryUnreadCount(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryUnreadCount, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChildCategories = `-- name: GetChildCategories :many
SELECT id, name, created_at, user_id, sort_order, parent_id FROM categories WHERE parent_id = ? AND user_id = ? ORDER BY sort_order, name
`

type GetChildCategoriesParams struct {
	ParentID *int64 `json:"parent_id"`
	UserID   *int64 `json:"user_id"`
}

func (q *Queries) GetChildCategories(ctx context.Context, arg GetChildCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getChildCategories, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UserID,
			&i.SortOrder,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at, user_id, content_filters, site_url FROM feeds WHERE id = ? AND user_id = ?
`

type GetFeedParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, arg.ID, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ContentFilters,
		&i.SiteUrl,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at, user_id, content_filters, site_url FROM feeds WHERE url = ? AND user_id = ?
`

type GetFeedByURLParams struct {
	Url    string `json:"url"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetFeedByURL(ctx context.Context, arg GetFeedByURLParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, arg.Url, arg.UserID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.FeedType,
		&i.ScraperModule,
		&i.ScraperConfig,
		&i.LastFetchedAt,
		&i.LastError,
		&i.FetchIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ContentFilters,
		&i.SiteUrl,
	)
	return i, err
}

const getFeedCategories = `-- name: GetFeedCategories :many
SELECT c.id, c.name, c.created_at, c.user_id, c.sort_order, c.parent_id FROM categories c
JOIN feed_categories fc ON c.id = fc.category_id
WHERE fc.feed_id = ?
`

func (q *Queries) GetFeedCategories(ctx context.Context, feedID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getFeedCategories, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UserID,
			&i.SortOrder,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedOwner = `-- name: GetFeedOwner :one
SELECT user_id FROM feeds WHERE id = ?
`

func (q *Queries) GetFeedOwner(ctx context.Context, id int64) (*int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedOwner, id)
	var user_id *int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getFeedUnreadCount = `-- name: GetFeedUnreadCount :one
SELECT COUNT(*) as count FROM articles WHERE feed_id = ? AND is_read = 0
`

func (q *Queries) GetFeedUnreadCount(ctx context.Context, feedID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedUnreadCount, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, created_at, user_id, sort_order, parent_id FROM categories WHERE user_id = ? ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context, userID *int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UserID,
			&i.SortOrder,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at, user_id, content_filters, site_url FROM feeds WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListFeeds(ctx context.Context, userID *int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ContentFilters,
			&i.SiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByCategory = `-- name: ListFeedsByCategory :many
SELECT f.id, f.name, f.url, f.feed_type, f.scraper_module, f.scraper_config, f.last_fetched_at, f.last_error, f.fetch_interval_minutes, f.created_at, f.updated_at, f.user_id, f.content_filters, f.site_url FROM feeds f
JOIN feed_categories fc ON f.id = fc.feed_id
WHERE fc.category_id = ? AND f.user_id = ?
ORDER BY f.name
`

type ListFeedsByCategoryParams struct {
	CategoryID int64  `json:"category_id"`
	UserID     *int64 `json:"user_id"`
}

func (q *Queries) ListFeedsByCategory(ctx context.Context, arg ListFeedsByCategoryParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByCategory, arg.CategoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ContentFilters,
			&i.SiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsToFetch = `-- name: ListFeedsToFetch :many
SELECT id, name, url, feed_type, scraper_module, scraper_config, last_fetched_at, last_error, fetch_interval_minutes, created_at, updated_at, user_id, content_filters, site_url FROM feeds 
WHERE last_fetched_at IS NULL 
   OR datetime(last_fetched_at, '+' || fetch_interval_minutes || ' minutes') < datetime('now')
ORDER BY last_fetched_at NULLS FIRST
`

func (q *Queries) ListFeedsToFetch(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsToFetch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ContentFilters,
			&i.SiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncategorizedFeeds = `-- name: ListUncategorizedFeeds :many
SELECT f.id, f.name, f.url, f.feed_type, f.scraper_module, f.scraper_config, f.last_fetched_at, f.last_error, f.fetch_interval_minutes, f.created_at, f.updated_at, f.user_id, f.content_filters, f.site_url FROM feeds f
WHERE f.user_id = ? AND NOT EXISTS (
  SELECT 1 FROM feed_categories fc WHERE fc.feed_id = f.id
)
ORDER BY f.name
`

func (q *Queries) ListUncategorizedFeeds(ctx context.Context, userID *int64) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listUncategorizedFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.FeedType,
			&i.ScraperModule,
			&i.ScraperConfig,
			&i.LastFetchedAt,
			&i.LastError,
			&i.FetchIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ContentFilters,
			&i.SiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedFromCategory = `-- name: RemoveFeedFromCategory :exec
DELETE FROM feed_categories WHERE feed_id = ? AND category_id = ?
`

type RemoveFeedFromCategoryParams struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) RemoveFeedFromCategory(ctx context.Context, arg RemoveFeedFromCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeFeedFromCategory, arg.FeedID, arg.CategoryID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ? WHERE id = ? AND user_id = ?
`

type UpdateCategoryParams struct {
	Name   string `json:"name"`
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.ID, arg.UserID)
	return err
}

const updateCategoryParent = `-- name: UpdateCategoryParent :exec
UPDATE categories SET parent_id = ?, sort_order = ? WHERE id = ? AND user_id = ?
`

type UpdateCategoryParentParams struct {
	ParentID  *int64 `json:"parent_id"`
	SortOrder *int64 `json:"sort_order"`
	ID        int64  `json:"id"`
	UserID    *int64 `json:"user_id"`
}

func (q *Queries) UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryParent,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories SET sort_order = ? WHERE id = ? AND user_id = ?
`

type UpdateCategorySortOrderParams struct {
	SortOrder *int64 `json:"sort_order"`
	ID        int64  `json:"id"`
	UserID    *int64 `json:"user_id"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorySortOrder, arg.SortOrder, arg.ID, arg.UserID)
	return err
}

const updateFeed = `-- name: UpdateFeed :exec
UPDATE feeds SET name = ?, url = ?, feed_type = ?, scraper_module = ?, scraper_config = ?, fetch_interval_minutes = ?, content_filters = ?, updated_at = datetime('now') WHERE id = ? AND user_id = ?
`

type UpdateFeedParams struct {
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	FeedType             string  `json:"feed_type"`
	ScraperModule        *string `json:"scraper_module"`
	ScraperConfig        *string `json:"scraper_config"`
	FetchIntervalMinutes *int64  `json:"fetch_interval_minutes"`
	ContentFilters       *string `json:"content_filters"`
	ID                   int64   `json:"id"`
	UserID               *int64  `json:"user_id"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeed,
		arg.Name,
		arg.Url,
		arg.FeedType,
		arg.ScraperModule,
		arg.ScraperConfig,
		arg.FetchIntervalMinutes,
		arg.ContentFilters,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateFeedLastFetched = `-- name: UpdateFeedLastFetched :exec
UPDATE feeds SET last_fetched_at = ?, last_error = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateFeedLastFetchedParams struct {
	LastFetchedAt *time.Time `json:"last_fetched_at"`
	LastError     *string    `json:"last_error"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateFeedLastFetched(ctx context.Context, arg UpdateFeedLastFetchedParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedLastFetched, arg.LastFetchedAt, arg.LastError, arg.ID)
	return err
}

const updateFeedSiteURL = `-- name: UpdateFeedSiteURL :exec
UPDATE feeds SET site_url = ? WHERE id = ?
`

type UpdateFeedSiteURLParams struct {
	SiteUrl string `json:"site_url"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateFeedSiteURL(ctx context.Context, arg UpdateFeedSiteURLParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedSiteURL, arg.SiteUrl, arg.ID)
	return err
}
