// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package dbgen

import (
	"context"
	"time"
)

const addToHistory = `-- name: AddToHistory :exec
INSERT INTO history_articles (user_id, article_id)
VALUES (?, ?)
ON CONFLICT(user_id, article_id) DO UPDATE SET viewed_at = CURRENT_TIMESTAMP
`

type AddToHistoryParams struct {
	UserID    int64 `json:"user_id"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) AddToHistory(ctx context.Context, arg AddToHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addToHistory, arg.UserID, arg.ArticleID)
	return err
}

const getHistoryCount = `-- name: GetHistoryCount :one
SELECT COUNT(*) FROM history_articles WHERE user_id = ?
`

func (q *Queries) GetHistoryCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHistoryCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listHistoryArticles = `-- name: ListHistoryArticles :many
SELECT a.id, a.feed_id, a.guid, a.title, a.url, a.author, a.content, a.summary,
       a.image_url, a.published_at, a.fetched_at, a.is_read, a.is_starred,
       f.name as feed_name, h.viewed_at
FROM history_articles h
JOIN articles a ON h.article_id = a.id
JOIN feeds f ON a.feed_id = f.id
WHERE h.user_id = ?
ORDER BY h.viewed_at DESC
LIMIT ? OFFSET ?
`

type ListHistoryArticlesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListHistoryArticlesRow struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
	FeedName    string     `json:"feed_name"`
	ViewedAt    time.Time  `json:"viewed_at"`
}

func (q *Queries) ListHistoryArticles(ctx context.Context, arg ListHistoryArticlesParams) ([]ListHistoryArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryArticlesRow{}
	for rows.Next() {
		var i ListHistoryArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Guid,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Content,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.IsRead,
			&i.IsStarred,
			&i.FeedName,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
