// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Article struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
}

type ArticleAlert struct {
	ID        int64     `json:"id"`
	ArticleID int64     `json:"article_id"`
	AlertID   int64     `json:"alert_id"`
	MatchedAt time.Time `json:"matched_at"`
	Dismissed int64     `json:"dismissed"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UserID    *int64    `json:"user_id"`
	SortOrder *int64    `json:"sort_order"`
	ParentID  *int64    `json:"parent_id"`
}

type CategoryExclusion struct {
	ID            int64     `json:"id"`
	CategoryID    int64     `json:"category_id"`
	ExclusionType string    `json:"exclusion_type"`
	Pattern       string    `json:"pattern"`
	IsRegex       *int64    `json:"is_regex"`
	CreatedAt     time.Time `json:"created_at"`
}

type CategorySetting struct {
	ID           int64     `json:"id"`
	CategoryID   int64     `json:"category_id"`
	SettingKey   string    `json:"setting_key"`
	SettingValue *string   `json:"setting_value"`
	CreatedAt    time.Time `json:"created_at"`
	UserID       *int64    `json:"user_id"`
}

type Feed struct {
	ID                   int64      `json:"id"`
	Name                 string     `json:"name"`
	Url                  string     `json:"url"`
	FeedType             string     `json:"feed_type"`
	ScraperModule        *string    `json:"scraper_module"`
	ScraperConfig        *string    `json:"scraper_config"`
	LastFetchedAt        *time.Time `json:"last_fetched_at"`
	LastError            *string    `json:"last_error"`
	FetchIntervalMinutes *int64     `json:"fetch_interval_minutes"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	UserID               *int64     `json:"user_id"`
	ContentFilters       *string    `json:"content_filters"`
	SiteUrl              string     `json:"site_url"`
	SkipRetention        int64      `json:"skip_retention"`
	ConsecutiveErrors    int64      `json:"consecutive_errors"`
}

type FeedCategory struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

type HistoryArticle struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ArticleID int64     `json:"article_id"`
	ViewedAt  time.Time `json:"viewed_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type NewsAlert struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	Pattern    string    `json:"pattern"`
	IsRegex    int64     `json:"is_regex"`
	MatchField string    `json:"match_field"`
	CreatedAt  time.Time `json:"created_at"`
}

type NntpCredential struct {
	UserID      int64     `json:"user_id"`
	Username    string    `json:"username"`
	PasswordEnc string    `json:"password_enc"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	KeyVersion  string    `json:"key_version"`
}

type QueueArticle struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ArticleID int64     `json:"article_id"`
	AddedAt   time.Time `json:"added_at"`
}

type ScraperModule struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Script      string    `json:"script"`
	ScriptType  string    `json:"script_type"`
	Enabled     *int64    `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserID      *int64    `json:"user_id"`
}

type SeenGuid struct {
	FeedID int64     `json:"feed_id"`
	Guid   string    `json:"guid"`
	SeenAt time.Time `json:"seen_at"`
}

type User struct {
	ID         int64     `json:"id"`
	ExternalID string    `json:"external_id"`
	Email      string    `json:"email"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type UserSetting struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}
