// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Article struct {
	ID          int64      `json:"id"`
	FeedID      int64      `json:"feed_id"`
	Guid        string     `json:"guid"`
	Title       string     `json:"title"`
	Url         *string    `json:"url"`
	Author      *string    `json:"author"`
	Content     *string    `json:"content"`
	Summary     *string    `json:"summary"`
	ImageUrl    *string    `json:"image_url"`
	PublishedAt *time.Time `json:"published_at"`
	FetchedAt   time.Time  `json:"fetched_at"`
	IsRead      *int64     `json:"is_read"`
	IsStarred   *int64     `json:"is_starred"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Feed struct {
	ID                   int64      `json:"id"`
	Name                 string     `json:"name"`
	Url                  string     `json:"url"`
	FeedType             string     `json:"feed_type"`
	ScraperModule        *string    `json:"scraper_module"`
	ScraperConfig        *string    `json:"scraper_config"`
	LastFetchedAt        *time.Time `json:"last_fetched_at"`
	LastError            *string    `json:"last_error"`
	FetchIntervalMinutes *int64     `json:"fetch_interval_minutes"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
}

type FeedCategory struct {
	FeedID     int64 `json:"feed_id"`
	CategoryID int64 `json:"category_id"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type ScraperModule struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Script      string    `json:"script"`
	ScriptType  string    `json:"script_type"`
	Enabled     *int64    `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
