// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nntp.sql

package dbgen

import (
	"context"
)

const deleteNNTPCredentials = `-- name: DeleteNNTPCredentials :exec
DELETE FROM nntp_credentials WHERE user_id = ?
`

func (q *Queries) DeleteNNTPCredentials(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNNTPCredentials, userID)
	return err
}

const getNNTPCredentials = `-- name: GetNNTPCredentials :one
SELECT user_id, username, password_enc, created_at, updated_at FROM nntp_credentials WHERE user_id = ?
`

func (q *Queries) GetNNTPCredentials(ctx context.Context, userID int64) (NntpCredential, error) {
	row := q.db.QueryRowContext(ctx, getNNTPCredentials, userID)
	var i NntpCredential
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNNTPCredentials = `-- name: UpsertNNTPCredentials :one
INSERT INTO nntp_credentials (user_id, username, password_enc)
VALUES (?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
  username     = excluded.username,
  password_enc = excluded.password_enc,
  updated_at   = CURRENT_TIMESTAMP
RETURNING user_id, username, password_enc, created_at, updated_at
`

type UpsertNNTPCredentialsParams struct {
	UserID      int64  `json:"user_id"`
	Username    string `json:"username"`
	PasswordEnc string `json:"password_enc"`
}

func (q *Queries) UpsertNNTPCredentials(ctx context.Context, arg UpsertNNTPCredentialsParams) (NntpCredential, error) {
	row := q.db.QueryRowContext(ctx, upsertNNTPCredentials, arg.UserID, arg.Username, arg.PasswordEnc)
	var i NntpCredential
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
