// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrapers.sql

package dbgen

import (
	"context"
)

const createScraperModule = `-- name: CreateScraperModule :one
INSERT INTO scraper_modules (name, description, script, script_type, user_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, script, script_type, enabled, created_at, updated_at, user_id
`

type CreateScraperModuleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Script      string  `json:"script"`
	ScriptType  string  `json:"script_type"`
	UserID      *int64  `json:"user_id"`
}

func (q *Queries) CreateScraperModule(ctx context.Context, arg CreateScraperModuleParams) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, createScraperModule,
		arg.Name,
		arg.Description,
		arg.Script,
		arg.ScriptType,
		arg.UserID,
	)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteScraperModule = `-- name: DeleteScraperModule :exec
DELETE FROM scraper_modules WHERE id = ? AND user_id = ?
`

type DeleteScraperModuleParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DeleteScraperModule(ctx context.Context, arg DeleteScraperModuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteScraperModule, arg.ID, arg.UserID)
	return err
}

const disableScraperModule = `-- name: DisableScraperModule :exec
UPDATE scraper_modules SET enabled = 0 WHERE id = ? AND user_id = ?
`

type DisableScraperModuleParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) DisableScraperModule(ctx context.Context, arg DisableScraperModuleParams) error {
	_, err := q.db.ExecContext(ctx, disableScraperModule, arg.ID, arg.UserID)
	return err
}

const enableScraperModule = `-- name: EnableScraperModule :exec
UPDATE scraper_modules SET enabled = 1 WHERE id = ? AND user_id = ?
`

type EnableScraperModuleParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) EnableScraperModule(ctx context.Context, arg EnableScraperModuleParams) error {
	_, err := q.db.ExecContext(ctx, enableScraperModule, arg.ID, arg.UserID)
	return err
}

const getScraperModule = `-- name: GetScraperModule :one
SELECT id, name, description, script, script_type, enabled, created_at, updated_at, user_id FROM scraper_modules WHERE id = ? AND user_id = ?
`

type GetScraperModuleParams struct {
	ID     int64  `json:"id"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetScraperModule(ctx context.Context, arg GetScraperModuleParams) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, getScraperModule, arg.ID, arg.UserID)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getScraperModuleByName = `-- name: GetScraperModuleByName :one
SELECT id, name, description, script, script_type, enabled, created_at, updated_at, user_id FROM scraper_modules WHERE name = ? AND user_id = ?
`

type GetScraperModuleByNameParams struct {
	Name   string `json:"name"`
	UserID *int64 `json:"user_id"`
}

func (q *Queries) GetScraperModuleByName(ctx context.Context, arg GetScraperModuleByNameParams) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, getScraperModuleByName, arg.Name, arg.UserID)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getScraperModuleInternal = `-- name: GetScraperModuleInternal :one
SELECT id, name, description, script, script_type, enabled, created_at, updated_at, user_id FROM scraper_modules WHERE name = ?
`

// Internal use only - gets scraper by name for background fetching
func (q *Queries) GetScraperModuleInternal(ctx context.Context, name string) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, getScraperModuleInternal, name)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listScraperModules = `-- name: ListScraperModules :many
SELECT id, name, description, script, script_type, enabled, created_at, updated_at, user_id FROM scraper_modules WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListScraperModules(ctx context.Context, userID *int64) ([]ScraperModule, error) {
	rows, err := q.db.QueryContext(ctx, listScraperModules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperModule{}
	for rows.Next() {
		var i ScraperModule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Script,
			&i.ScriptType,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScraperModule = `-- name: UpdateScraperModule :exec
UPDATE scraper_modules SET name = ?, description = ?, script = ?, script_type = ?, updated_at = datetime('now') WHERE id = ? AND user_id = ?
`

type UpdateScraperModuleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Script      string  `json:"script"`
	ScriptType  string  `json:"script_type"`
	ID          int64   `json:"id"`
	UserID      *int64  `json:"user_id"`
}

func (q *Queries) UpdateScraperModule(ctx context.Context, arg UpdateScraperModuleParams) error {
	_, err := q.db.ExecContext(ctx, updateScraperModule,
		arg.Name,
		arg.Description,
		arg.Script,
		arg.ScriptType,
		arg.ID,
		arg.UserID,
	)
	return err
}
