// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrapers.sql

package dbgen

import (
	"context"
)

const createScraperModule = `-- name: CreateScraperModule :one
INSERT INTO scraper_modules (name, description, script, script_type)
VALUES (?, ?, ?, ?)
RETURNING id, name, description, script, script_type, enabled, created_at, updated_at
`

type CreateScraperModuleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Script      string  `json:"script"`
	ScriptType  string  `json:"script_type"`
}

func (q *Queries) CreateScraperModule(ctx context.Context, arg CreateScraperModuleParams) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, createScraperModule,
		arg.Name,
		arg.Description,
		arg.Script,
		arg.ScriptType,
	)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScraperModule = `-- name: DeleteScraperModule :exec
DELETE FROM scraper_modules WHERE id = ?
`

func (q *Queries) DeleteScraperModule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScraperModule, id)
	return err
}

const disableScraperModule = `-- name: DisableScraperModule :exec
UPDATE scraper_modules SET enabled = 0 WHERE id = ?
`

func (q *Queries) DisableScraperModule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableScraperModule, id)
	return err
}

const enableScraperModule = `-- name: EnableScraperModule :exec
UPDATE scraper_modules SET enabled = 1 WHERE id = ?
`

func (q *Queries) EnableScraperModule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, enableScraperModule, id)
	return err
}

const getScraperModule = `-- name: GetScraperModule :one
SELECT id, name, description, script, script_type, enabled, created_at, updated_at FROM scraper_modules WHERE id = ?
`

func (q *Queries) GetScraperModule(ctx context.Context, id int64) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, getScraperModule, id)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScraperModuleByName = `-- name: GetScraperModuleByName :one
SELECT id, name, description, script, script_type, enabled, created_at, updated_at FROM scraper_modules WHERE name = ?
`

func (q *Queries) GetScraperModuleByName(ctx context.Context, name string) (ScraperModule, error) {
	row := q.db.QueryRowContext(ctx, getScraperModuleByName, name)
	var i ScraperModule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Script,
		&i.ScriptType,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScraperModules = `-- name: ListScraperModules :many
SELECT id, name, description, script, script_type, enabled, created_at, updated_at FROM scraper_modules ORDER BY name
`

func (q *Queries) ListScraperModules(ctx context.Context) ([]ScraperModule, error) {
	rows, err := q.db.QueryContext(ctx, listScraperModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScraperModule{}
	for rows.Next() {
		var i ScraperModule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Script,
			&i.ScriptType,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScraperModule = `-- name: UpdateScraperModule :exec
UPDATE scraper_modules SET name = ?, description = ?, script = ?, script_type = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateScraperModuleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Script      string  `json:"script"`
	ScriptType  string  `json:"script_type"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateScraperModule(ctx context.Context, arg UpdateScraperModuleParams) error {
	_, err := q.db.ExecContext(ctx, updateScraperModule,
		arg.Name,
		arg.Description,
		arg.Script,
		arg.ScriptType,
		arg.ID,
	)
	return err
}
