// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package dbgen

import (
	"context"
)

const deleteUserSetting = `-- name: DeleteUserSetting :exec
DELETE FROM user_settings WHERE user_id = ? AND key = ?
`

type DeleteUserSettingParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteUserSetting(ctx context.Context, arg DeleteUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSetting, arg.UserID, arg.Key)
	return err
}

const getUserSetting = `-- name: GetUserSetting :one
SELECT value FROM user_settings WHERE user_id = ? AND key = ?
`

type GetUserSettingParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetUserSetting(ctx context.Context, arg GetUserSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserSetting, arg.UserID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserSettings = `-- name: GetUserSettings :many
SELECT key, value FROM user_settings WHERE user_id = ?
`

type GetUserSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetUserSettings(ctx context.Context, userID int64) ([]GetUserSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserSettingsRow{}
	for rows.Next() {
		var i GetUserSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSetting = `-- name: SetUserSetting :exec
INSERT INTO user_settings (user_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
`

type SetUserSettingParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) SetUserSetting(ctx context.Context, arg SetUserSettingParams) error {
	_, err := q.db.ExecContext(ctx, setUserSetting, arg.UserID, arg.Key, arg.Value)
	return err
}
