// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (external_id, email)
VALUES (?, ?)
RETURNING id, external_id, email, created_at, last_seen_at
`

type CreateUserParams struct {
	ExternalID string `json:"external_id"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ExternalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getNewsletterToken = `-- name: GetNewsletterToken :one
SELECT value FROM user_settings WHERE user_id = ? AND key = 'newsletter_token'
`

func (q *Queries) GetNewsletterToken(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterToken, userID)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (external_id, email)
VALUES (?, ?)
ON CONFLICT(external_id) DO UPDATE SET 
  last_seen_at = CURRENT_TIMESTAMP,
  email = excluded.email
RETURNING id, external_id, email, created_at, last_seen_at
`

type GetOrCreateUserParams struct {
	ExternalID string `json:"external_id"`
	Email      string `json:"email"`
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser, arg.ExternalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, email, created_at, last_seen_at FROM users WHERE external_id = ?
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserIDByNewsletterToken = `-- name: GetUserIDByNewsletterToken :one
SELECT user_id FROM user_settings WHERE key = 'newsletter_token' AND value = ?
`

func (q *Queries) GetUserIDByNewsletterToken(ctx context.Context, value string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByNewsletterToken, value)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const listAllUserIDs = `-- name: ListAllUserIDs :many
SELECT id FROM users
`

func (q *Queries) ListAllUserIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNewsletterToken = `-- name: SetNewsletterToken :exec
INSERT INTO user_settings (user_id, key, value) VALUES (?, 'newsletter_token', ?)
ON CONFLICT(user_id, key) DO UPDATE SET value = excluded.value
`

type SetNewsletterTokenParams struct {
	UserID int64  `json:"user_id"`
	Value  string `json:"value"`
}

func (q *Queries) SetNewsletterToken(ctx context.Context, arg SetNewsletterTokenParams) error {
	_, err := q.db.ExecContext(ctx, setNewsletterToken, arg.UserID, arg.Value)
	return err
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :exec
UPDATE users SET last_seen_at = CURRENT_TIMESTAMP, email = ? WHERE id = ?
`

type UpdateUserLastSeenParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUserLastSeen(ctx context.Context, arg UpdateUserLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSeen, arg.Email, arg.ID)
	return err
}
