// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (external_id, email)
VALUES (?, ?)
RETURNING id, external_id, email, created_at, last_seen_at
`

type CreateUserParams struct {
	ExternalID string `json:"external_id"`
	Email      string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ExternalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (external_id, email)
VALUES (?, ?)
ON CONFLICT(external_id) DO UPDATE SET 
  last_seen_at = CURRENT_TIMESTAMP,
  email = excluded.email
RETURNING id, external_id, email, created_at, last_seen_at
`

type GetOrCreateUserParams struct {
	ExternalID string `json:"external_id"`
	Email      string `json:"email"`
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser, arg.ExternalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, email, created_at, last_seen_at FROM users WHERE external_id = ?
`

func (q *Queries) GetUserByExternalID(ctx context.Context, externalID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalID, externalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :exec
UPDATE users SET last_seen_at = CURRENT_TIMESTAMP, email = ? WHERE id = ?
`

type UpdateUserLastSeenParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUserLastSeen(ctx context.Context, arg UpdateUserLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSeen, arg.Email, arg.ID)
	return err
}
