export default [
  {
    files: ["srv/static/**/*.js"],
    ignores: ["srv/static/**/*.test.js", "srv/static/**/*.browser.test.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        URLSearchParams: "readonly",
        URL: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Event: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        DOMParser: "readonly",
        DOMException: "readonly",
        File: "readonly",
        PopStateEvent: "readonly",
        Window: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        getComputedStyle: "readonly",
        scrollTo: "readonly",
        // Service Worker
        self: "readonly",
        caches: "readonly",
        clients: "readonly",
        Response: "readonly",
        Request: "readonly",
      },
    },
    rules: {
      // Possible errors
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-unexpected-multiline": "error",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],

      // Best practices
      "eqeqeq": ["warn", "smart"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-redeclare": "error",
      "no-unused-vars": ["warn", {
        args: "none",
        caughtErrors: "none",
      }],
      "no-undef": "error",
      "no-use-before-define": ["warn", { functions: false, classes: false }],
    },
  },
  // Unit test files (jsdom environment via Vitest)
  {
    files: ["srv/static/**/*.test.js"],
    ignores: ["srv/static/**/*.browser.test.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        URLSearchParams: "readonly",
        URL: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Event: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        DOMParser: "readonly",
        DOMException: "readonly",
        File: "readonly",
        PopStateEvent: "readonly",
        Window: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        getComputedStyle: "readonly",
        scrollTo: "readonly",
        Response: "readonly",
        Request: "readonly",
        // Vitest globals
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        vi: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
    rules: {
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-unexpected-multiline": "error",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "eqeqeq": ["warn", "smart"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-redeclare": "error",
      "no-unused-vars": ["warn", {
        args: "none",
        caughtErrors: "none",
      }],
      "no-undef": "error",
      "no-use-before-define": ["warn", { functions: false, classes: false }],
    },
  },
  // Browser test files (Playwright environment via Vitest browser mode)
  {
    files: ["srv/static/**/*.browser.test.js", "tests/layout/**/*.test.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        URLSearchParams: "readonly",
        URL: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Event: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        DOMParser: "readonly",
        DOMException: "readonly",
        File: "readonly",
        PopStateEvent: "readonly",
        Window: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        getComputedStyle: "readonly",
        scrollTo: "readonly",
        Response: "readonly",
        Request: "readonly",
        // Vitest globals
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        vi: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        // Vitest browser mode globals
        commands: "readonly",
        page: "readonly",
      },
    },
    rules: {
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-unexpected-multiline": "error",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "eqeqeq": ["warn", "smart"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-redeclare": "error",
      "no-unused-vars": ["warn", {
        args: "none",
        caughtErrors: "none",
      }],
      "no-undef": "error",
      "no-use-before-define": ["warn", { functions: false, classes: false }],
    },
  },
];
